version: '1.0'
services:
  client:
    build: ./client
    container_name: shop_frontend
    ports: 
       - 3000:80
    networks:
       - my_network
    volumes:
       - ./client:/app

  backend:
    build: ./backend
    container_name: shop_backend
    ports: 
       - 3001:3001
    networks:
       - my_network
    volumes:
       - ./client:/app

networks:
   my_network:
